clementwzk/OpenCalc

.idea/deploymentTargetDropDown.xml, .idea/misc.xml, app/build.gradle, app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt, app/src/main/java/com/darkempire78/opencalculator/Themes.kt, app/src/main/res/values/styles.xml
=> Added Material You Support

app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt
Fix app freeze issue with large numbers closes #14
- Introduce Kotlin Coroutine to do all the calculations and string manipulation on the background thread
- Make sure that UI related changes run on the main thread
=> Fix app freeze issue to close #14

app/src/main/res/valuea-az/strings.xml, app/src/main/res/values-az/strings.xml, app/src/main/res/values-ru/strings.xml
Fixed Azerbaijan language file (no problem now)
=> Add Russian Language

app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt, build.gradle
- Handle un-mathematical percent (#35)
- small MainActivity factorization
- update to gradle 7.2.2
This is the first time I try any Android / Kotlin / etc development, so any suggestion is totally appreciated!
_Also it would be nice to have some real unit tests for this kind of feature maybe?
And I see that the Kotlin gradle plugin is deprecated, but my knowledge is still too limited about that.. :smile:_
=> Unmathematical percent

app/build.gradle, app/src/androidTest/java/com/darkempire78/opencalculator/ExampleInstrumentedTest.kt, app/src/main/java/com/darkempire78/opencalculator/AboutActivity.kt, app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt, app/src/main/java/com/darkempire78/opencalculator/MyPreferences.kt, app/src/main/java/com/darkempire78/opencalculator/NumberFormatter.kt, app/src/main/java/com/darkempire78/opencalculator/Themes.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-az/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-gr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/com/darkempire78/opencalculator/ExampleUnitTest.kt, build.gradle, gradle.properties
- Removed `kotlin-android-extensions` and changed the Activities code accordingly (https://developer.android.com/topic/libraries/view-binding/migration)
- Upgraded dependencies, replaced deprecated `jcenter()` with `mavenCentral()`, disabled `Jetifier`
- Cleaned the code (mostly using `ktlint`)
I still have that warning left that I couldn't find how to fix, it seems `getPackageInfo` is the right way to do?!
_This PR should be safe as most of those changes are recommended by Android Studio or the official documentation, and everything seems to work properly;
although don't forget that I've started to learn Kotlin yesterday :smile:_
=> Remove deprecated kotlin-android-extensions & update/clean code

app/src/main/res/values-fa/strings.xml
=> Persian translation!

README.md, readme/turkish.readme.md
=> Added Turkish README.md and shortcut 

app/src/main/res/values-el/strings.xml
- Improved file structure
- Added new strings
=> Update greek translation

app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt, app/src/main/res/values-el/strings.xml, app/src/main/res/values/strings.xml
This PR should fix #145 and #146.
Fix for #145:
The fix for #146 works, just didn't have the time to capture the video.
=> Fix negative infinity strings not being handled

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/values-el/strings.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
Android studio was complaining that the gradle version is old.
=> Update greek translation & gradle

app/src/main/res/layout-land/activity_main.xml, app/src/main/res/layout-sw720dp-land/activity_main.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml
I'm sorry, but I didn't spot a few instances of the word "devide". I have now done a find and replace so everything should be good.
=> Fix typo (again)

app/src/main/java/com/darkempire78/opencalculator/Calculator.kt, app/src/main/java/com/darkempire78/opencalculator/Expression.kt, app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt, app/src/main/res/layout-land/activity_main.xml, app/src/main/res/layout-sw720dp-land/activity_main.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
Hello and congratulations for releasing v2 of this awesome app! I've made a few improvements to it. Let me know if you want me to change something.
- sinus/cosinus (French) -> sine/cosine (English)
- Remove an unused string and reorganize existing ones
- Updated greek translation
- Only store the result to history if it's a number (and not NaN or +/- Infinity), just like other calculator apps do
- Display an error when dividing by 0 (the previous approach was to output +/- Infinity, which is only correct if we are talking about limits)
- Display an error on ln0 for the same reason as above
- Minor code refactoring and simplification
=> Multiple improvements

app/build.gradle
Update the dependencies into latest version as per 15 feb 2023
Changes details :-
1. appcompat :1.5.1  into 1.6.1
2. Android material : 1.7.0 into 1.8.0
3. Test. ext:junit: 1.1.4  into 1.1.5
4. Test espresso-core : 3.5.0  into 3.5.1
=> dependencies update

app/build.gradle, app/src/main/java/com/darkempire78/opencalculator/AboutActivity.kt, app/src/main/java/com/darkempire78/opencalculator/Expression.kt, app/src/main/java/com/darkempire78/opencalculator/HistoryAdapter.kt, app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt, app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml
I think that adding some color can greatly improve the overall UX of the app. This PR changes the text color to red if an error occurs and then resets it if a change is detected. Also adds another improvements, like removing deprecated methods and cleanup.
=> Change text color on error & Other improvements

app/src/main/java/com/darkempire78/opencalculator/Calculator.kt, app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt, app/src/main/java/com/darkempire78/opencalculator/NumberFormatter.kt, app/src/main/java/com/darkempire78/opencalculator/OpenCalcApp.kt
- Changed variable name (error_status -> errorStatus)
- Only calculate factorial if it's needed (it's not negative or infinity)
Also, I'm sorry for committing unrelated stuff to the previous PR. It's just that I feel I have overloaded you with PRs every now and then... :)
=> Minor refactor

app/src/main/java/com/darkempire78/opencalculator/Calculator.kt
arctan has a domain of all real numbers so the domain error is incorrect.
Please let me know if any other corrections are needed.
=> Fix arctan domain error

app/src/main/java/com/darkempire78/opencalculator/HistoryAdapter.kt, app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt
Fixes cursor location when a symbol is inserted into the calculation. This resolves issues 218 and 329.
=> Fix cursor location on symbol input

fastlane/metadata/android/en-US/changelogs/11.txt, fastlane/metadata/android/en-US/changelogs/12.txt, fastlane/metadata/android/en-US/changelogs/15.txt, fastlane/metadata/android/en-US/changelogs/16.txt, fastlane/metadata/android/en-US/changelogs/18.txt, fastlane/metadata/android/en-US/changelogs/19.txt, fastlane/metadata/android/en-US/changelogs/20.txt, fastlane/metadata/android/en-US/changelogs/25.txt, fastlane/metadata/android/en-US/changelogs/28.txt, fastlane/metadata/android/en-US/changelogs/3.txt, fastlane/metadata/android/en-US/changelogs/31.txt, fastlane/metadata/android/en-US/changelogs/32.txt, fastlane/metadata/android/en-US/changelogs/33.txt, fastlane/metadata/android/en-US/changelogs/34.txt, fastlane/metadata/android/en-US/changelogs/35.txt, fastlane/metadata/android/en-US/changelogs/37.txt, fastlane/metadata/android/en-US/changelogs/38.txt, fastlane/metadata/android/en-US/changelogs/4.txt, fastlane/metadata/android/en-US/changelogs/5.txt, fastlane/metadata/android/en-US/changelogs/7.txt, fastlane/metadata/android/en-US/changelogs/8.txt, fastlane/metadata/android/en-US/changelogs/9.txt, fastlane/metadata/android/pt-BR/changelogs/11.txt, fastlane/metadata/android/pt-BR/changelogs/12.txt, fastlane/metadata/android/pt-BR/changelogs/3.txt, fastlane/metadata/android/pt-BR/changelogs/5.txt
=> From "Fix:" and "Fixed:" to "Fixes:"

fastlane/metadata/android/en-US/changelogs/10.txt, fastlane/metadata/android/en-US/changelogs/11.txt, fastlane/metadata/android/en-US/changelogs/12.txt, fastlane/metadata/android/en-US/changelogs/13.txt, fastlane/metadata/android/en-US/changelogs/14.txt, fastlane/metadata/android/en-US/changelogs/15.txt, fastlane/metadata/android/en-US/changelogs/3.txt, fastlane/metadata/android/en-US/changelogs/5.txt, fastlane/metadata/android/en-US/changelogs/6.txt, fastlane/metadata/android/en-US/changelogs/9.txt
"Change:"
"Fixes:"
"Improvements:"
"New:"
"Updated:
Most of them are plural, if they can (new and updated cant be plural - uncountable and different time)
So lets make them all plural, if they can - "Change:" to "Changes:"
=> "Change:" to "Changes:"

app/src/main/res/layout/activity_about.xml, app/src/main/res/values-be/strings.xml, app/src/main/res/values-bs/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-mk/strings.xml, app/src/main/res/values-ml/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sat/strings.xml, app/src/main/res/values-sr/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-ti/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
I think you forgot to change it
Related to #323
=> "about_category_other" to "about_category_info"

app/src/main/java/com/darkempire78/opencalculator/HistoryAdapter.kt, app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt, app/src/main/res/values/strings.xml
Fixes: #378 
I didnt find any more labels for translations, but I moved one string to its section (the clean up part)
=> Add translations + clean up

fastlane/metadata/android/en-US/changelogs/28.txt, fastlane/metadata/android/en-US/changelogs/33.txt
Fixes: #331
I had to delete more
I hope that is enough
=> Fix lengths of changelogs

README.md, fastlane/metadata/android/en-US/full_description.txt
I didnt know that OpenCalc has Quick Settings Tile. Its should be in features
=> Add Quick Settings Tile to features

app/src/main/java/com/darkempire78/opencalculator/NumberFormatter.kt
this pull requests fixes two issues:
1. #275
2. #342
=> fix some formatting issues

app/src/main/res/values-night/styles.xml, app/src/main/res/values/styles.xml
I tested it on my device
Fixes: #352 
Fixes: #327 
But doesnt work for #353 
https://www.reddit.com/r/androiddev/comments/r5e99c/how_do_you_handle_forced_dark_mode_and_apps_not/
=> Fix Xiaomi devices with force Dark theme

app/src/main/java/com/darkempire78/opencalculator/Themes.kt
=> Add private to Amoled theme index

app/build.gradle
Updating from compileSdkVersion to compileSdk aligns with the latest Android Gradle Plugin standards, ensuring compatibility with new tools and features
[developer.android](https://developer.android.com/build)
=> feat: Updating from compileSdkVersion to compileSdk 

app/src/main/java/com/darkempire78/opencalculator/Calculator.kt
=> fix log crash when x < 0

app/src/main/res/layout-land/activity_main.xml, app/src/main/res/layout-sw720dp-land/activity_main.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml
Enabled accessibility for talkback feature for several unlabeled buttons. Couldn't screen record because talkback didn't catch up with the screen recorder.
=> Fixed Issue #405 - Several buttons are not labeled properly

app/src/main/java/com/darkempire78/opencalculator/calculator/Calculator.kt
A simple fix for negative exponents returning incorrect. Test now passes.
=> Fix issue with negative exponents

app/src/main/res/layout/activity_main.xml
Moved the buttons by default, 0 is below 2, backspace below 1 and dot below 3
=> moved buttons #505

app/src/main/java/com/darkempire78/opencalculator/activities/MainActivity.kt
This should take care of the decimal problem.
=> Issue #536 - New pointButton() code to fix decimal entry issue.

app/src/main/java/com/darkempire78/opencalculator/MyPreferences.kt, app/src/main/java/com/darkempire78/opencalculator/activities/MainActivity.kt, app/src/main/java/com/darkempire78/opencalculator/activities/SettingsActivity.kt, app/src/main/java/com/darkempire78/opencalculator/calculator/parser/NumberFormatter.kt, app/src/main/res/xml/root_preferences.xml, app/src/test/java/com/darkempire78/opencalculator/NumberFormatterTest.kt
This PR implements the idea of having number system as discussed in #319 
Conversation: https://github.com/Darkempire78/OpenCalc/issues/319#issuecomment-2622425958
Tasks:
=> feat: impl numbering system (Internation + Indian)

README.md, app/src/main/res/values/strings.xml
- Updated menu strings in `strings.mxl` 
- Corrected unclosed `<div>` tag in `README.md`
Let me know if any further changes are needed :D
Fixes #547
=> Fix: Updated menu string and closed layout divs

app/src/main/java/com/darkempire78/opencalculator/calculator/parser/NumberFormatter.kt
Fixed issue when .9999^9999 showed .9,999^9999 instead of .9999^9,999. replaceFirst() would see .9999 and replace it instead of the following 9999 after the '^'.
=> Issue #560
